Repository Respect/Validation, pull requests merged in 2018-06, with the labels that each got.

#974 Remove dead code "AbstractInterval"
  library/Rules/AbstractInterval.php
Labels: Enhancement

#975 Add return type to "reportError()"
  library/Rules/AbstractEnvelope.php
  library/Rules/AbstractRule.php
  library/Rules/Instance.php
  library/Validatable.php
Labels: Backward Compatibility Break

#976 Make sure templates are always string
  library/Rules/AbstractRule.php
  library/Validatable.php
Labels: Backward Compatibility Break

#977 Apply contribution guidelines to "IterableType" rule
  docs/IterableType.md
  library/Exceptions/IterableTypeException.php
  library/Helpers/CanValidateIterable.php
  library/Rules/Each.php
  library/Rules/IterableType.php
  tests/integration/rules/iterableType.phpt
  tests/integration/rules/iterableType_1.phpt
  tests/integration/rules/iterableType_2.phpt
  tests/integration/rules/iterableType_3.phpt
  tests/integration/rules/iterableType_4.phpt
  tests/integration/rules/iterableType_5.phpt
  tests/unit/Rules/IterableTypeTest.php
Labels: Backward Compatibility Break, Enhancement

#983 Apply contribution guidelines to "Uppercase" rule
  docs/Uppercase.md
  library/Exceptions/UppercaseException.php
  library/Rules/Uppercase.php
  tests/integration/rules/uppercase.phpt
  tests/unit/Rules/UppercaseTest.php
Labels: Backward Compatibility Break, Enhancement

#989 Apply contribution guidelines to "Positive" rule
  docs/Positive.md
  library/Exceptions/PositiveException.php
  library/Rules/Positive.php
  tests/integration/rules/positive.phpt
  tests/unit/Rules/PositiveTest.php
Labels: Backward Compatibility Break, Enhancement

#1002 Apply contribution guidelines to "Bsn" rule
  library/Exceptions/BsnException.php
  library/Rules/Bsn.php
  tests/integration/rules/bsn.phpt
  tests/integration/rules/bsn_1.phpt
  tests/integration/rules/bsn_2.phpt
  tests/integration/rules/bsn_3.phpt
  tests/unit/Rules/BsnTest.php
Labels: Backward Compatibility Break, Enhancement

#973 Add Countable support to comparable trait
  docs/Between.md
  docs/ComparableValues.md
  docs/GreaterThan.md
  docs/LessThan.md
  docs/Max.md
  docs/Min.md
  library/Helpers/ComparisonHelper.php
  tests/library/Stubs/CountableStub.php
  tests/unit/Rules/BetweenTest.php
  tests/unit/Rules/GreaterThanTest.php
  tests/unit/Rules/LessThanTest.php
  tests/unit/Rules/MaxTest.php
  tests/unit/Rules/MinTest.php
Labels: Enhancement

#1032 Create "Equivalent" rule
  docs/Contains.md
  docs/Equals.md
  docs/Equivalent.md
  docs/Identical.md
  docs/VALIDATORS.md
  library/Exceptions/EquivalentException.php
  library/Rules/Equivalent.php
  library/Validator.php
  tests/integration/rules/equivalent.phpt
  tests/unit/Rules/EquivalentTest.php
Labels: New Validator
