Repository Respect/Validation, pull requests merged in 2018-10, with the labels that each got.

#1138 Create "Isbn" rule
  docs/list-of-rules.md
  docs/rules/Isbn.md
  library/Exceptions/IsbnException.php
  library/Rules/Isbn.php
  library/Validator.php
  tests/integration/rules/isbn.phpt
  tests/unit/Rules/IsbnTest.php
Labels: New Validator

#1150 Add support for specific versions of UUID
  docs/rules/Uuid.md
  library/Exceptions/UuidException.php
  library/Rules/Uuid.php
  library/Validator.php
  tests/integration/rules/uuid.phpt
  tests/unit/Rules/UuidTest.php
Labels: Enhancement

#1153 Use variadics "AbstractFilterRule" rule
  docs/rules/Alnum.md
  docs/rules/Alpha.md
  docs/rules/Cntrl.md
  docs/rules/Consonant.md
  docs/rules/Digit.md
  docs/rules/Graph.md
  docs/rules/Printable.md
  docs/rules/Punct.md
  docs/rules/Space.md
  docs/rules/Vowel.md
  docs/rules/Xdigit.md
  library/Rules/AbstractFilterRule.php
  library/Rules/Alnum.php
  library/Rules/Alpha.php
  library/Rules/Cntrl.php
  library/Rules/Consonant.php
  library/Rules/Digit.php
  library/Rules/Graph.php
  library/Rules/Printable.php
  library/Rules/Punct.php
  library/Rules/Space.php
  library/Rules/Vowel.php
  library/Rules/Xdigit.php
  library/Validator.php
  tests/unit/Rules/AbstractFilterRuleTest.php
  tests/unit/Rules/AlnumTest.php
  tests/unit/Rules/AlphaTest.php
  tests/unit/Rules/CntrlTest.php
  tests/unit/Rules/ConsonantTest.php
  tests/unit/Rules/DigitTest.php
  tests/unit/Rules/GraphTest.php
  tests/unit/Rules/PrintableTest.php
  tests/unit/Rules/PunctTest.php
  tests/unit/Rules/SpaceTest.php
  tests/unit/Rules/VowelTest.php
  tests/unit/Rules/XdigitTest.php
Labels: Backward Compatibility Break, Enhancement

#1154 Add support to Twitch on "VideoUrl" rule
  docs/rules/VideoUrl.md
  library/Rules/VideoUrl.php
  tests/unit/Rules/VideoUrlTest.php
Labels: Enhancement
