Repository Respect/Validation, pull requests merged in 2018-08, with the labels that each got.

#1064 Remove unnecessary validation from "Factory" class
  library/Factory.php
Labels: Enhancement

#1063 Few improvements on the Validator class
  library/Validator.php
Labels: Backward Compatibility Break, Enhancement

#1066 Apply contribution guidelines to "NestedValidationException"
  library/Exceptions/GroupedValidationException.php
  library/Exceptions/KeySetException.php
  library/Exceptions/NestedValidationException.php
  library/Exceptions/RecursiveExceptionIterator.php
  library/Rules/AbstractComposite.php
  library/Rules/AbstractRelated.php
  library/Rules/AllOf.php
  library/Rules/AnyOf.php
  library/Rules/Domain.php
  library/Rules/Each.php
  library/Rules/NoneOf.php
  library/Rules/OneOf.php
  library/Rules/Zend.php
  library/Validatable.php
  tests/integration/not_with_recursion.phpt
  tests/integration/not_without_recursion.phpt
  tests/unit/Exceptions/NestedValidationExceptionTest.php
Labels: Backward Compatibility Break, Enhancement

#1074 Apply contribution guidelines to "In" rule
  library/Exceptions/InException.php
  library/Rules/In.php
  tests/integration/rules/in.phpt
  tests/unit/Rules/InTest.php
Labels: Backward Compatibility Break, Enhancement

#1075 Do not trigger PHP errors in the "Call" rule
  docs/Call.md
  library/Exceptions/CallException.php
  library/Rules/Call.php
  library/Validator.php
  tests/integration/rules/call.phpt
  tests/unit/Rules/CallTest.php
Labels: Backward Compatibility Break, Enhancement

#1076 Remove support "egulias/email-validator" ~1.0
  library/Rules/Email.php
  tests/unit/Rules/EmailTest.php
Labels: Backward Compatibility Break, Enhancement

#1077 Change how "Sf" rule works
  composer.json
  docs/Sf.md
  library/Exceptions/SfException.php
  library/Rules/Sf.php
  library/Validator.php
  tests/integration/rules/sf.phpt
  tests/unit/Rules/SfTest.php
Labels: Backward Compatibility Break, Enhancement

#1081 Setup PHPStan (PHP Static Analysis Tool)
  .gitignore
  .travis.yml
  composer.json
  library/Exceptions/ValidationException.php
  library/Rules/Domain.php
  library/Validator.php
  phpstan.neon.dist
  tests/integration/intVal.phpt
  tests/integration/issue-799.phpt
  tests/library/Rules/Stub.php
  tests/unit/Helpers/DateTimeHelperTest.php
  tests/unit/Helpers/UndefinedHelperTest.php
  tests/unit/Rules/CreditCardTest.php
  tests/unit/Rules/FactorTest.php
  tests/unit/Rules/FileTest.php
  tests/unit/Rules/PhpLabelTest.php
  tests/unit/Rules/ReadableTest.php
  tests/unit/Rules/SymbolicLinkTest.php
  tests/unit/Rules/WritableTest.php
Labels: Enhancement

#1085 Fix wrong behavior of "Date" rule
  library/Rules/Date.php
  tests/unit/Rules/DateTest.php
Labels: Patch

#1086 Update "PostalCode" list
  library/Rules/PostalCode.php
  tests/unit/Rules/PostalCodeTest.php
Labels: Patch
